feat: creating card component
alboompro/boom-components pull request #51
Opened 2021-06-30 13:38 UTC by kszinhu

### **Task:** Card Component.

**Goals:** 

- [x] Create card component.

---
#### Card images

- Basic Use  
![image](https://user-images.githubusercontent.com/66069923/123968747-e5907d80-d98d-11eb-92fc-2f85308fc98d.png)

- Simple card and `Bordered`  
![image](https://user-images.githubusercontent.com/66069923/123968867-06f16980-d98e-11eb-8af9-1f014be3782c.png)

- `Hoverable` Card  
![image](https://user-images.githubusercontent.com/66069923/123968998-2ab4af80-d98e-11eb-850e-3b8ff15f6ffc.png)

- `Cover`  
![image](https://user-images.githubusercontent.com/66069923/123969264-70717800-d98e-11eb-9bce-60540e0c5ff2.png)

- Card with `Tabs`  
![image](https://user-images.githubusercontent.com/66069923/123969389-8b43ec80-d98e-11eb-8cb2-5c99f8b42c74.png)

- and more  
![image](https://user-images.githubusercontent.com/66069923/123969478-a57dca80-d98e-11eb-8398-d6bd3b43e9f9.png)

![image](https://user-images.githubusercontent.com/66069923/123969582-bcbcb800-d98e-11eb-9575-47d6e02d566c.png)

2021-07-05 14:45 UTC, kszinhu commented
## Fixed card component test

> In the test was used shallow checking the props of the component.

![image](https://user-images.githubusercontent.com/66069923/124488561-6385c780-dd86-11eb-80cd-7c4200e72cd7.png)

2021-07-06 12:21 UTC, elisoncampos commented on src/data-display/card/Card.js
> +import Tabs from "../tabs/Tabs";
A dependência de utilizar ou não tabs não deve existir por padrão, as funcionalidades do card são opt-in e não opt-out (o que nem é o caso pois não conseguimos desativar o carregamento de tabs)

2021-07-06 12:23 UTC, elisoncampos commented on src/data-display/card/Card.js
> +  ...props
Seria interessante ter uma prop para esconder o titulo, ou esconder o titulo caso a prop title não seja passada, o que faria ela se tornar opcional.

2021-07-06 12:24 UTC, elisoncampos commented on src/data-display/card/Card.js
> +      ) : null}
É recomendado não utilizar ifs ternários dentro de ifs ternários pois dificulta a leitura do código

2021-07-06 12:30 UTC, elisoncampos requested changes
A implementação está correta mas acredito que possamos melhorar o código e diminuir a complexidade do componente, vamos tentar melhorá-lo antes de subir para produção.

2021-07-06 12:30 UTC, elisoncampos commented on src/data-display/card/Card.js
> +      ) : null}
Seria mais interessante alterar esta parte para um Footer, onde o utilizador do componente poderia passar um node como conteúdo e o mesmo seria renderizado nesse bloco.

2021-07-06 12:30 UTC, elisoncampos commented on src/data-display/card/Card.js
> +  };
Essa função vai ser desnecessária quando implementarmos o footer, lembrar de remover.

2021-07-06 12:30 UTC, elisoncampos commented on src/data-display/card/Card.js
> +import { Props } from "docz";
Remover essa linha.

2021-07-07 12:58 UTC, kszinhu commented
## Applied requested changes in the component

  
> - [x] Removed any meta reference, loading.
> - [x] Refactoring to decrease complexity

_Is an example:_  
```js
import Meta from "./Meta.js";
import Tabs from "../tabs/Tabs.js";
```

```js
return (
    <CardStyle {...StyleProps} style={{ ...style }}>
      {title && (
        <HeadStyle {...HeadProps}>
          <TitleStyle {...HeadProps}>{title}</TitleStyle>
        </HeadStyle>
      )}
      {cover}
      {children && <BodyStyle {...BodyProps}>{children}</BodyStyle>}
      {footer}
    </CardStyle>
  );
```

> - [x] Improving component documentation after changes

![image](https://user-images.githubusercontent.com/66069923/124761657-65779400-df08-11eb-8f1a-24e74d81520a.png)

2021-07-08 15:18 UTC, elisoncampos approved these changes
Boa, ficou muito melhor.

2021-07-08 15:18 UTC, merged